import type { LocaleStrings } from "@docx-editor.dev/i18n"

type CompleteLocale = Omit<LocaleStrings, "_lang"> & { _lang: string }

// Українська локалізація інтерфейсу редактора (@docx-editor.dev).
// У пакеті локалі uk немає, тому словник ведеться вручну й типізується
// повним каталоном en — компілятор вимагає перекладу кожного ключа.
// Термінологія вирівняна на українську локалізацію Microsoft Word:
// колонтитул, виноска, міжрядковий інтервал, обтікання текстом тощо.
export const uk: CompleteLocale = {
  _lang: "uk",
  common: {
    cancel: "Скасувати",
    apply: "Застосувати",
    close: "Закрити",
    comment: "Коментар",
    dismiss: "Приховати",
  },
  disabledReason: {
    editorNotReady: "Редактор ще не готовий",
    notWired: "Цей елемент не підключено до команди редактора",
    viewing: "Документ відкрито лише для перегляду",
    trackedOnly: "Цей документ дозволяє зміни лише у режимі виправлень",
    noDocument: "Документ не завантажено",
    noReviewAuthors: "У цьому документі немає авторів рецензування",
    noContentControl: "Не вибрано елемент керування вмістом",
    noCopiedFormatting: "Спочатку скопіюйте форматування",
    noDrawing: "Не вибрано зображення",
    drawingLocked: "Це зображення заблоковано",
    commentSelection: "Перед додаванням коментаря виділіть фрагмент",
    mergeUnsupported: "Об'єднання комірок не підтримується",
    splitUnsupported: "Розбиття комірки не підтримується",
    imageSuggesting: "Зміни зображень недоступні в режимі пропозицій",
    invalidValue: "Це значення недійсне для цієї команди",
    unavailable: "Ця команда недоступна",
    bodyOnlySectionBreak: "Розриви розділів вставляються в основну частину документа.",
    bodyOnlyToc: "Зміст вставляється в основну частину документа.",
    bodyOnlyNote: "Виноски та кінцеві виноски додаються з основної частини документа.",
    furnitureOnlyPageField: "Відкрийте колонтитул, щоб вставити номер сторінки.",
    suggestingSectionBreak:
      "Вимкніть режим пропозицій, щоб вставити цей розрив розділу. Він змінює початок наступного розділу, а це не можна запропонувати.",
    tableCellSectionBreak: "Розриви розділів розміщуються поза таблицею.",
    lockedSectionBreak:
      "Заблокований або пов'язаний елемент керування вмістом містить наступний розділ, тому цей розрив не може його змінити.",
    lockedContentBreak:
      "Елемент керування вмістом блокує цей текст, тому розрив розділу тут неможливий.",
    nothingToCopyFormatting: "Виділіть текст, щоб скопіювати його форматування",
    nothingToPaint: "Виділіть текст, щоб застосувати форматування",
  },
  toolbar: {
    ariaLabel: "Панель інструментів форматування",
    file: "Файл",
    format: "Формат",
    insert: "Вставити",
    review: "Рецензування",
    open: "Відкрити",
    openShortcut: "Ctrl+O",
    save: "Зберегти",
    saveShortcut: "Ctrl+S",
    print: "Друк",
    printShortcut: "Ctrl+P",
    pageSetup: "Параметри сторінки",
    leftToRight: "Текст зліва направо",
    rightToLeft: "Текст справа наліво",
    image: "Зображення",
    table: "Таблиця",
    insertTable: "Вставити таблицю",
    break: "Розрив",
    insertFootnote: "Вставити виноску",
    insertEndnote: "Вставити кінцеву виноску",
    pageBreak: "Розрив сторінки",
    sectionBreakNextPage: "Розрив розділу (з наступної сторінки)",
    sectionBreakContinuous: "Розрив розділу (без розриву сторінки)",
    tableOfContents: "Зміст",
    watermark: "Підкладка",
    help: "Довідка",
    reportIssue: "Повідомити про проблему",
  },
  toc: {
    refresh: "Оновити зміст",
    refreshPageNumbers: "Оновити номери сторінок",
  },
  formattingBar: {
    groups: {
      history: "Історія",
      zoom: "Масштаб",
      styles: "Стилі",
      font: "Шрифт",
      textFormatting: "Форматування тексту",
      script: "Індекси",
      alignment: "Вирівнювання",
      listFormatting: "Форматування списків",
      format: "Формат",
      image: "Зображення",
      table: "Таблиця",
    },
    undo: "Скасувати",
    undoShortcut: "Скасувати (Ctrl+Z)",
    redo: "Повторити",
    redoShortcut: "Повторити (Ctrl+Y)",
    bold: "Напівжирний",
    boldShortcut: "Напівжирний (Ctrl+B)",
    italic: "Курсив",
    italicShortcut: "Курсив (Ctrl+I)",
    underline: "Підкреслений",
    underlineShortcut: "Підкреслений (Ctrl+U)",
    strikethrough: "Закреслений",
    fontColor: "Колір шрифту",
    highlightColor: "Колір виділення тексту",
    insertLink: "Вставити посилання",
    insertLinkShortcut: "Вставити посилання (Ctrl+K)",
    superscript: "Верхній індекс",
    superscriptShortcut: "Верхній індекс (Ctrl+Shift+=)",
    subscript: "Нижній індекс",
    subscriptShortcut: "Нижній індекс (Ctrl+=)",
    imageProperties: "Властивості зображення",
    imagePropertiesShortcut: "Властивості зображення (альтернативний текст, межа)...",
    imageWrap: "Обтікання текстом",
    altText: "Альтернативний текст",
    clearFormatting: "Очистити форматування",
    formatPainter: "Формат за зразком",
    formatPainterShortcut: "Формат за зразком (Ctrl+Alt+C, Ctrl+Alt+V)",
    commentsAndChanges: "Коментарі та зміни",
    more: "Більше",
    unavailableInPreview: "Недоступно в цій збірці перегляду",
  },
  alignment: {
    alignLeft: "По лівому краю",
    alignLeftShortcut: "Ctrl+L",
    center: "По центру",
    centerShortcut: "Ctrl+E",
    alignRight: "По правому краю",
    alignRightShortcut: "Ctrl+R",
    justify: "По ширині",
    justifyShortcut: "Ctrl+J",
  },
  lists: {
    ariaLabel: "Форматування списків",
    typeAriaLabel: "Тип списку",
    indentationAriaLabel: "Відступ списку",
    bulletList: "Маркований список",
    numberedList: "Нумерований список",
    decreaseIndent: "Зменшити відступ",
    increaseIndent: "Збільшити відступ",
  },
  lineSpacing: {
    label: "Міжрядковий інтервал",
    single: "Одинарний",
    double: "Подвійний",
    lineSpacingTitle: "Міжрядковий інтервал: {label}",
    blockSpacingRules: "Інтервал між абзацами",
    addSpaceBefore: "Додати інтервал перед абзацем",
    removeSpaceBefore: "Прибрати інтервал перед абзацем",
    addSpaceAfter: "Додати інтервал після абзацу",
    removeSpaceAfter: "Прибрати інтервал після абзацу",
    options: "Параметри міжрядкового інтервалу…",
  },
  styles: {
    selectAriaLabel: "Вибрати стиль абзацу",
    normalText: "Звичайний текст",
    title: "Назва",
    subtitle: "Підназва",
    heading1: "Заголовок 1",
    heading2: "Заголовок 2",
    heading3: "Заголовок 3",
  },
  font: {
    selectAriaLabel: "Вибрати шрифт",
    sansSerif: "Без засічок",
    serif: "З засічками",
    monospace: "Моноширинний",
    documentFonts: "Шрифти документа",
  },
  fontSize: {
    decrease: "Зменшити розмір шрифту",
    increase: "Збільшити розмір шрифту",
    label: "Розмір шрифту",
    listLabel: "Розміри шрифтів",
  },
  zoom: {
    ariaLabel: "Масштаб: {label}",
    zoomOut: "Зменшити",
    zoomIn: "Збільшити",
    zoomLevel: "Масштаб",
    automatic: "Автоматично",
    fitWidth: "За шириною",
  },
  colorPicker: {
    highlightColors: "Кольори виділення",
    customColor: "Інший колір",
    noColor: "Без кольору",
    automatic: "Автоматично",
    themeColors: "Кольори теми",
    theme: {
      background1: "Фон 1",
      text1: "Текст 1",
      background2: "Фон 2",
      text2: "Текст 2",
      accent1: "Акцент 1",
      accent2: "Акцент 2",
      accent3: "Акцент 3",
      accent4: "Акцент 4",
      accent5: "Акцент 5",
      accent6: "Акцент 6",
    },
    standardColors: "Стандартні кольори",
    colors: {
      black: "Чорний",
      darkRed: "Темночервоний",
      red: "Червоний",
      orange: "Помаранчевий",
      yellow: "Жовтий",
      darkYellow: "Темножовтий",
      green: "Зелений",
      darkGreen: "Темнозелений",
      blue: "Синій",
      darkBlue: "Темносиній",
      purple: "Фіолетовий",
      white: "Білий",
      lightGreen: "Світлозелений",
      lightBlue: "Світлоблакитний",
      darkGray: "Темносірий",
      cyan: "Бірюзовий",
      darkCyan: "Темнобірюзовий",
      magenta: "Пурпуровий",
      darkMagenta: "Темнопурпуровий",
      lightGray: "Світлосірий",
      brightGreen: "Яскравозелений",
    },
    apply: "Застосувати",
  },
  dialogs: {
    imageProperties: {
      title: "Властивості зображення",
      altText: "Альтернативний текст",
      altTextPlaceholder: "Опишіть це зображення для доступності...",
      textWrapping: "Обтікання текстом",
      dimensions: "Розміри",
      widthLabel: "Ширина:",
      heightLabel: "Висота:",
      lockAspectRatio: "Зберігати пропорції",
    },
    imagePosition: {
      relativeOptions: {
        page: "Сторінка",
        column: "Стовпець",
        margin: "Поле",
        character: "Знак",
        paragraph: "Абзац",
        line: "Рядок",
      },
    },
    pageSetup: {
      title: "Параметри сторінки",
      pageSize: "РОЗМІР СТОРІНКИ",
      sizeLabel: "Розмір",
      custom: "Власний",
      orientation: "Орієнтація",
      portrait: "Книжкова",
      landscape: "Альбомна",
      margins: "ПОЛЯ",
      top: "Зверху",
      bottom: "Знизу",
      left: "Ліворуч",
      right: "Праворуч",
      applyTo: "Застосувати до",
      applyToDocument: "До всього документа",
      applyToSection: "До цього розділу",
      pageSizes: {
        letter: 'Letter (8.5" × 11")',
        a4: 'A4 (8.27" × 11.69")',
        legal: 'Legal (8.5" × 14")',
        a3: 'A3 (11.69" × 16.54")',
        a5: 'A5 (5.83" × 8.27")',
        b5: 'B5 (6.93" × 9.84")',
        executive: 'Executive (7.25" × 10.5")',
      },
    },
    footnoteProperties: {
      title: "Параметри виносок і кінцевих виносок",
      footnotes: "Виноски",
      endnotes: "Кінцеві виноски",
      position: "Положення",
      numberFormat: "Формат номера",
      numbering: "Нумерація",
      footnotePositions: {
        bottomOfPage: "Унизу сторінки",
        belowText: "Під текстом",
      },
      endnotePositions: {
        endOfDocument: "У кінці документа",
        endOfSection: "У кінці розділу",
      },
      numberingOptions: {
        continuous: "Продовжувати",
        restartSection: "Починати з кожним розділом",
        restartPage: "Починати з кожною сторінкою",
      },
      formats: {
        decimal: "1, 2, 3, ...",
        lowerRoman: "i, ii, iii, ...",
        upperRoman: "I, II, III, ...",
      },
    },
    paragraph: {
      title: "Абзац",
      general: "Загальне",
      alignment: "Вирівнювання",
      alignLeft: "Ліворуч",
      alignCenter: "По центру",
      alignRight: "Праворуч",
      alignJustify: "По ширині",
      indentation: "Відступ",
      beforeText: "Перед текстом",
      afterText: "Після тексту",
      special: "Спеціальний",
      specialNone: "(немає)",
      specialFirstLine: "Перший рядок",
      specialHanging: "Виступ",
      by: "на",
      spacing: "Інтервал",
      spaceBefore: "Перед",
      spaceAfter: "Після",
      lineSpacing: "Міжрядковий інтервал",
      ruleMultiple: "Множинний",
      ruleAtLeast: "Мінімум",
      ruleExactly: "Точно",
      at: "Значення",
      contextualSpacing: "Не додавати інтервал між абзацами одного стилю",
      pagination: "Розбивка на сторінки",
      keepNext: "Не відривати від наступного",
      keepLines: "Не розривати рядки",
      widowControl: "Заборона висячих рядків",
      pageBreakBefore: "Розрив сторінки перед абзацом",
      unitInches: "in",
      unitPoints: "pt",
      ok: "OK",
      cancel: "Скасувати",
      tabStops: "Позиції табуляції",
      tabPosition: "Позиція",
      tabAlignment: "Вирівнювання",
      tabLeader: "Заповнювач",
      tabAdd: "Установити",
      tabClearAll: "Очистити всі",
      tabRemove: "Очистити",
      tabNone: "Немає",
      tabAlignLeft: "Ліворуч",
      tabAlignCenter: "По центру",
      tabAlignRight: "Праворуч",
      tabAlignDecimal: "Десяткова",
      tabAlignBar: "Розділювач",
      tabLeaderDot: "Крапки",
      tabLeaderHyphen: "Тире",
      tabLeaderUnderscore: "Підкреслення",
      tabEmpty: "Позиції табуляції не задано.",
      tabPositionLabel: "{position} in",
      tabRemoveAt: "Очистити позицію табуляції {position} in",
      refused: "Ці значення не можна застосувати тут.",
      tabMixed: "Вибрані абзаци мають різні позиції табуляції.",
      mixed: "Різні",
      notShown: "Тут не відображається",
    },
  },
  comments: {
    unknown: "Невідомий",
    addComment: "Додати коментар...",
    replyPlaceholder: "Відповідайте або згадуйте інших через @",
    resolve: "Вирішити",
    reopen: "Повторно відкрити",
  },
  revisions: {
    paragraphMarkInserted: "Вставлено розрив абзацу",
    paragraphMarkDeleted: "Видалено розрив абзацу",
    paragraphMarkMovedFrom: "Розрив абзацу переміщено геть",
    paragraphMarkMovedTo: "Розрив абзацу переміщено сюди",
    runPropertiesChanged: "Змінено форматування тексту",
  },
  contextMenu: {
    ariaLabel: "Контекстне меню",
    cut: "Вирізати",
    cutShortcut: "Ctrl+X",
    copy: "Копіювати",
    copyShortcut: "Ctrl+C",
    paste: "Вставити",
    pasteShortcut: "Ctrl+V",
    pasteWithoutFormatting: "Вставити без форматування",
    pasteWithoutFormattingShortcut: "Ctrl+Shift+V",
    copyFormatting: "Копіювати форматування",
    copyFormattingShortcut: "Ctrl+Alt+C",
    pasteFormatting: "Вставити форматування",
    pasteFormattingShortcut: "Ctrl+Alt+V",
    delete: "Видалити",
    deleteShortcut: "Del",
    selectAll: "Вибрати все",
    selectAllShortcut: "Ctrl+A",
    editCustomNode: "Редагувати {label}",
    removeCustomNode: "Видалити {label}",
  },
  documentOutline: {
    ariaLabel: "Структура документа",
    closeAriaLabel: "Закрити структуру",
    closeTitle: "Закрити структуру",
    title: "Структура",
    noHeadings: "Заголовків не знайдено. Додайте заголовки до документа, щоб побачити їх тут.",
  },
  navigation: {
    ariaLabel: "Навігація документом",
    title: "Навігація",
    openAriaLabel: "Відкрити навігацію",
    openTitle: "Навігація",
    closeAriaLabel: "Закрити навігацію",
    closeTitle: "Закрити навігацію",
    tabs: {
      headings: "Заголовки",
      find: "Пошук",
    },
    headings: {
      noHeadings: "Заголовків не знайдено. Додайте заголовки до документа, щоб побачити їх тут.",
    },
    find: {
      placeholder: "Пошук у документі",
      inputAriaLabel: "Пошук у документі",
      clearAriaLabel: "Очистити пошук",
      previousAriaLabel: "Попередній результат",
      nextAriaLabel: "Наступний результат",
      matchCase: "З урахуванням регістру",
      wholeWord: "Тільки цілі слова",
      optionsAriaLabel: "Параметри пошуку",
      resultsAriaLabel: "Результати пошуку",
      noResults: "Немає результатів",
      searching: "Пошук…",
      counter: "Результат {current} із {total}",
      counterTruncated: "Результат {current} із {total}+",
      total: "{total, plural, one {# результат} few {# результати} many {# результатів} other {# результатів}}",
      totalTruncated: "{total, plural, other {#+ результатів}}",
    },
  },
  viewer: {
    pageIndicator: "{current} із {total}",
  },
  titleBar: {
    untitled: "Без назви",
    documentNameAriaLabel: "Назва документа",
    menuBarAriaLabel: "Рядок меню",
  },
  errors: {
    unableToParse: "Не вдалося розібрати документ",
    somethingWentWrong: "Щось пішло не так",
    errorDescription:
      "Під час відображення цього компонента сталася помилка. Спробуйте ще раз або зверніться до підтримки, якщо проблема не зникає.",
    errorLabel: "Помилка:",
    componentStack: "Стек компонентів:",
    tryAgain: "Спробувати ще раз",
    showDetails: "Показати подробиці",
    hideDetails: "Приховати подробиці",
  },
  table: {
    insertRowAbove: "Вставити рядок вище",
    insertRowBelow: "Вставити рядок нижче",
    insertColumnLeft: "Вставити стовпець ліворуч",
    insertColumnRight: "Вставити стовпець праворуч",
    deleteRow: "Видалити рядок",
    deleteColumn: "Видалити стовпець",
    deleteTable: "Видалити таблицю",
    selectTable: "Вибрати всю таблицю",
    mergeCells: "Об'єднати комірки",
    splitCell: "Розділити комірку",
    editingTools: "Інструменти редагування таблиці",
    label: "Таблиця:",
    cellFillColor: "Колір заливки комірки",
    borderColor: "Колір меж",
    borderWidth: "Товщина меж",
    clearCellFill: "Прибрати заливку комірки",
    borderStyles: {
      single: "Суцільна",
      dashed: "Штрихова",
      dotted: "Пунктирна",
      double: "Подвійна",
      triple: "Потрійна",
      thick: "Товста",
    },
    borderWidths: {
      halfPt: "0.5 pt",
      onePt: "1 pt",
      oneHalfPt: "1.5 pt",
      twoPt: "2 pt",
      threePt: "3 pt",
    },
    borders: {
      all: "Усі межі",
      outside: "Зовнішні межі",
      inside: "Внутрішні межі",
      none: "Без меж",
      top: "Верхня межа",
      bottom: "Нижня межа",
      left: "Ліва межа",
      right: "Права межа",
      styleAriaLabel: "Стиль меж",
      tooltip: "Межі",
    },
    moreOptions: "Більше параметрів таблиці",
  },
  tableAdvanced: {
    verticalAlignment: "Вертикальне вирівнювання",
    top: "Верх",
    middle: "Середина",
    bottom: "Низ",
    toggleNoWrap: "Переключити заборону переносу",
    toggleHeaderRow: "Переключити рядок заголовків",
    distributeColumns: "Рівномірно розподілити стовпці",
    autoFit: "Автопідбір за вмістом",
    tableProperties: "Властивості таблиці...",
    tableAlignment: "Вирівнювання таблиці",
    alignTableLeft: "Вирівняти таблицю ліворуч",
    alignTableCenter: "Вирівняти таблицю по центру",
    alignTableRight: "Вирівняти таблицю праворуч",
  },
  imageTransform: {
    tooltip: "Трансформування",
    rotateClockwise: "Повернути за годинниковою стрілкою",
    rotateCounterClockwise: "Повернути проти годинникової стрілки",
    flipHorizontal: "Відобразити горизонтально",
    flipVertical: "Відобразити вертикально",
  },
  imageWrap: {
    inline: "У рядку з текстом",
    square: "По контуру",
    tight: "Щільне",
    through: "Крізь",
    floatLeft: "По контуру зліва",
    floatRight: "По контуру справа",
    topAndBottom: "Зверху та знизу",
    behindText: "За текстом",
    inFrontOfText: "Перед текстом",
    tooltipPrefix: "Обтікання: {label}",
    targets: {
      inline: "У рядку з текстом",
      square: "По контуру",
      squareLeft: "По контуру зліва",
      squareRight: "По контуру справа",
      tight: "Щільне",
      through: "Крізь",
      topAndBottom: "Зверху та знизу",
      behind: "За текстом",
      inFront: "Перед текстом",
    },
    menu: {
      inLineWithText: "У рядку з текстом",
      squareLeft: "По контуру зліва",
      squareRight: "По контуру справа",
      ariaLabel: "Параметри розташування зображення",
    },
  },
  imageInsert: {
    errors: {
      emptyFile: "Вибраний файл порожній.",
      invalidSignature: "Файл не є підтримуваним зображенням PNG, JPEG або GIF.",
      unsupportedFormat: "Цей формат зображення не підтримується для вставлення.",
      oversize: "Зображення перевищує максимально дозволений розмір.",
      refused: "Зображення не вдалося вставити.",
    },
  },
  imageProperties: {
    units: {
      points: "pt",
    },
    hyperlink: "Гіперпосилання",
    crop: "Обрізання",
    cropLeft: "Ліворуч (%)",
    cropTop: "Зверху (%)",
    cropRight: "Праворуч (%)",
    cropBottom: "Знизу (%)",
    resetNaturalSize: "Скинути до початкового розміру",
    nonPictureHint: "Обрізання та скидання до початкового розміру доступні лише для малюнків.",
    errors: {
      invalidDimensions: "Введіть додатні значення ширини та висоти.",
      invalidCrop: "Значення обрізання мають бути відсотками від 0 до 100.",
      invalidPosition: "Введіть коректні значення горизонтальної та вертикальної позиції.",
      refused: "Ці властивості не вдалося застосувати.",
    },
    position: "Положення",
    positionUnavailable: "Положення доступне лише для плаваючих зображень.",
    positionLocked: "Цей малюнок не можна переміщувати.",
    horizontalOffset: "Горизонтальний зсув",
    verticalOffset: "Вертикальний зсув",
    relativeToHorizontal: "Відносно (горизонталь)",
    relativeToVertical: "Відносно (вертикаль)",
  },
  imageAltText: {
    panelTitle: "Альтернативний текст",
    title: "Назва",
    description: "Опис",
  },
  editor: {
    showDocumentOutline: "Показати структуру документа",
    linkCopied: "Посилання скопійовано в буфер обміну",
    fontSubstitutionNotice:
      "Деякі шрифти цього документа недоступні, тому показано замінники: {fonts}",
  },
  hyperlinkPopup: {
    displayTextPlaceholder: "Текст, що відображається",
    urlPlaceholder: "https://example.com",
    urlLabel: "URL",
    copyLink: "Копіювати посилання",
    editLink: "Редагувати посилання",
    removeLink: "Видалити посилання",
    openLink: "Відкрити посилання",
    apply: "Застосувати",
    cancel: "Скасувати",
    insertTitle: "Вставити посилання",
    editTitle: "Редагувати посилання",
    inertTarget: "Це посилання веде туди, куди редактор не переходитиме",
    bookmarkTarget: "Переходить до місця в цьому документі",
    refused: "Це посилання не вдалося застосувати. Перевірте адресу й спробуйте ще раз.",
  },
  equationPopup: {
    title: "Редагувати формулу",
    inputLabel: "Лінійний запис формули",
    placeholder: "Введіть формулу",
    apply: "Застосувати",
    delete: "Видалити",
    refused: "Цю формулу не вдалося застосувати. Перевірте синтаксис і спробуйте ще раз.",
  },
  contentControl: {
    group: "Елементи керування вмістом",
    showAll: "Показувати межі елементів керування вмістом",
    formFill: "Режим заповнення форм",
    inspector: "Властивості елемента керування вмістом",
    remove: "Видалити елемент керування вмістом",
    inspectorPanel: {
      title: "Елемент керування вмістом",
      alias: "Назва",
      tag: "Тег",
      type: "Тип",
      lock: "Блокування",
      placeholder: "Заповнювач",
      bound: "Прив'язано до даних",
      empty: "—",
      yes: "Так",
      no: "Ні",
      boundNote: "Цей елемент прив'язано до зовнішніх даних. Редагування заборонено.",
      lockedNote: "Редагування вмісту цього елемента заблоковано.",
    },
    types: {
      richText: "Форматований текст",
      plainText: "Звичайний текст",
      checkbox: "Прапорець",
      dropdown: "Розкривний список",
      comboBox: "Поле зі списком",
      date: "Дата",
      picture: "Малюнок",
      repeatingSection: "Повторюваний розділ",
    },
    lock: {
      unlocked: "Розблоковано",
      sdtLocked: "Елемент керування заблоковано",
      contentLocked: "Вміст заблоковано",
      sdtContentLocked: "Елемент керування та вміст заблоковано",
    },
  },
  headerFooter: {
    chromeAriaLabel: "Редагування колонтитулів",
    header: "Верхній колонтитул",
    footer: "Нижній колонтитул",
    firstPageHeader: "Верхній колонтитул першої сторінки",
    firstPageFooter: "Нижній колонтитул першої сторінки",
    evenPageHeader: "Верхній колонтитул парних сторінок",
    evenPageFooter: "Нижній колонтитул парних сторінок",
    sameAsPrevious: "Як у попередньому",
    sameAsPreviousHint: "Зміни застосуються також до сторінок попереднього розділу.",
    options: "Параметри",
    differentFirstPage: "Особливий колонтитул для першої сторінки",
    differentOddEven: "Різні колонтитули для парних і непарних сторінок",
    differentOddEvenHint: "Застосовується до всього документа.",
    linkToPrevious: "Як у попередньому розділі",
    unlinkFromPrevious: "Від'єднати від попереднього розділу",
    headerDistance: "Відстань верхнього колонтитула від краю",
    footerDistance: "Відстань нижнього колонтитула від краю",
    removeHeader: "Видалити верхній колонтитул",
    removeFooter: "Видалити нижній колонтитул",
    insertPageNumber: "Вставити номер поточної сторінки",
    insertTotalPages: "Вставити загальну кількість сторінок",
    insertSectionPages: "Вставити кількість сторінок розділу",
    insertPageXofY: "Вставити «сторінка X із Y»",
  },
  image: {
    unsupportedFormat: "Непідтримуваний формат зображення ({format})",
    nonPictureGraphic: "Непідтримувана графіка ({kind})",
    missingResource: "Зображення відсутнє",
    externalResource: "Зовнішнє зображення не завантажено",
    invalidResource: "Недійсне зображення",
    contentMismatch: "Вміст зображення не відповідає його типу",
    decodeFailed: "Зображення не вдалося декодувати",
    resourceLimit: "Зображення перевищує обмеження розміру",
    pendingResource: "Завантаження зображення",
  },
  imageOverlay: {
    selection: "Вибране зображення",
    handle: {
      n: "Змінити розмір: верхній край",
      ne: "Змінити розмір: верхній правий кут",
      e: "Змінити розмір: правий край",
      se: "Змінити розмір: нижній правий кут",
      s: "Змінити розмір: нижній край",
      sw: "Змінити розмір: нижній лівий кут",
      w: "Змінити розмір: лівий край",
      nw: "Змінити розмір: верхній лівий кут",
    },
  },
  ruler: {
    horizontal: "Горизонтальна лінійка",
    vertical: "Вертикальна лінійка",
    firstLineIndent: "Відступ першого рядка",
    hangingIndent: "Виступ",
    leftIndent: "Відступ ліворуч",
    rightIndent: "Відступ праворуч",
    topMargin: "Верхнє поле",
    bottomMargin: "Нижнє поле",
  },
  loading: {
    label: "Завантаження",
  },
  notes: {
    delete: "Видалити виноску",
    convertToEndnote: "Перетворити на кінцеву виноску",
    convertToFootnote: "Перетворити на звичайну виноску",
    scope: "Застосувати до",
    scopeDocument: "До всього документа",
    scopeSection: "До цього розділу",
    previewFallback: "Виноска",
    chromeAriaLabel: "Редагування виносок",
    editingRegion: "{kind} {number}",
    footnoteKind: "Виноска",
    endnoteKind: "Кінцева виноска",
    convertAllFootnotes: "Перетворити всі виноски на кінцеві виноски",
    convertAllEndnotes: "Перетворити всі кінцеві виноски на виноски",
    inheritedValue: "(успадковано)",
  },
  reviewers: {
    label: "Рецензенти",
    markupOptions: "Параметри розмітки",
    all: "Усі",
  },
  editingMode: {
    label: "Режим редагування",
    editing: "Редагування",
    editingHint: "Редагуйте документ безпосередньо",
    suggesting: "Пропозиції",
    suggestingHint: "Зміни фіксуються як пропозиції",
    viewing: "Перегляд",
    viewingHint: "Лише читання, без змін",
  },
  collaboration: {
    participants: "Люди в цьому документі",
    moreParticipants:
      "{count, plural, one {ще # особа} few {ще # особи} many {ще # осіб} other {ще # осіб}}",
  },
  collaborationDemo: {
    title: "Перевірка однорангової співпраці",
    subtitle: "Запустіть цю сторінку на двох машинах і відкрийте спільне посилання на кімнату.",
    name: "Ім'я для показу",
    room: "ID або посилання на кімнату",
    create: "Створити кімнату",
    join: "Приєднатися до кімнати",
    share: "Поділіться цим посиланням для приєднання",
    copy: "Копіювати посилання",
    copied: "Посилання скопійовано",
    connection: "Стан кімнати",
    peers: "Підключені учасники",
    disconnect: "Від'єднатися",
    reconnect: "Повторно під'єднатися",
    undo: "Скасувати",
    redo: "Повторити",
    save: "Зберегти DOCX",
    scope: "Ця кімната реплікує весь документ: текст, форматування, таблиці, колонтитули.",
    warning:
      "Публічна сигнальна інфраструктура призначена для тестування. Посилання на кімнату не є контролем доступу, сховищем чи гарантією з'єднання.",
    failed: "Перевірку співпраці не вдалося запустити.",
    connect: "Під'єднатися",
    online: "у мережі",
    dialogTitle: "Співпраця над цим документом",
    dialogSubtitle: "Поділіться цим документом або приєднайтеся до кімнати, яку вам надіслали.",
    roomTitle: "Кімната співпраці",
    roomSubtitle: "Усі тут бачать зміни документа та курсори в реальному часі.",
    shareDocument: "Поділитися цим документом",
    shareDescription: "Створіть кімнату та скопіюйте посилання-запрошення.",
    joinExisting: "Приєднатися до наявної кімнати",
    joinDescription: "Відкрийте посилання на кімнату від іншого учасника.",
    inviteLink: "Посилання-запрошення",
    connected: "Під'єднано",
    reconnecting: "Повторне під'єднання",
    outOfSync: "Розсинхронізовано. Перезавантажте, щоб приєднатися знову.",
    outOfSyncShort: "Розсинхронізовано",
    person: "особа",
    people: "особи",
    you: "Ви",
    leave: "Покинути кімнату",
    done: "Готово",
    close: "Закрити вікно співпраці",
    back: "Назад",
    creating: "Створення кімнати…",
    connecting: "Під'єднання…",
    enterRoom: "Введіть посилання на кімнату або її ID.",
    connectFailed: "Не вдалося під'єднатися до кімнати.",
    leaveFailed: "Не вдалося покинути кімнату.",
    guest: "Гість",
    caretPages: "{count, plural, one {# сторінка} few {# сторінки} many {# сторінок} other {# сторінок}}",
  },
  review: {
    ariaLabel: "Рецензування",
    empty: "Немає змін або коментарів",
    accept: "Прийняти",
    reject: "Відхилити",
    deleteComment: "Видалити коментар",
    discardChange: "Відкинути зміну",
    reply: "Відповісти",
    inserted: "Додано",
    deleted: "Видалено",
    movedFrom: "Переміщено звідси",
    movedTo: "Переміщено сюди",
    structural: "Змінено структуру документа",
    replyRefused: "Не вдалося надіслати відповідь",
    showPane: "Показати коментарі",
    resolved: "Вирішено",
    showResolvedComment: "Показати вирішений коментар",
    replaced: "Замінено",
    replacedWith: "на",
    commentRefused: "Не вдалося додати коментар",
  },
}
